# Generated by Django 4.2.1 on 2023-05-13 04:24
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.TextField()),
                ("body", models.TextField()),
                ("book", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="book.book")),
            ],
        ),
    ]
