# Generated by Django 4.2.1 on 2023-05-13 04:47
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_bookpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "from_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="from_page", to="book.bookpage"
                    ),
                ),
                (
                    "to_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="to_page", to="book.bookpage"
                    ),
                ),
            ],
            options={
                "unique_together": {("from_page", "to_page")},
            },
        ),
    ]
