# Generated by Django 4.2.1 on 2023-05-13 04:49
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0003_pagelink"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagelink",
            name="name",
            field=models.TextField(default="???"),
            preserve_default=False,
        ),
    ]
