# Generated by Django 4.2.1 on 2023-05-13 05:24
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0004_pagelink_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagelink",
            name="from_page",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="book.bookpage"),
        ),
    ]
