# Generated by Django 4.2.1 on 2023-05-13 05:33
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0005_alter_pagelink_from_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="first_page",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="first_page", to="book.bookpage"
            ),
        ),
    ]
