# Generated by Django 4.2.1 on 2023-05-29 12:35
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_first_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_art',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
