# Generated by Django 4.2.1 on 2023-05-30 10:14
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_book_cover_art_bookprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='bookprogress',
            name='items',
            field=models.ManyToManyField(to='book.item'),
        ),
    ]
