# Generated by Django 4.2.1 on 2023-05-30 12:04
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_item_bookprogress_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpage',
            name='items',
            field=models.ManyToManyField(to='book.item'),
        ),
    ]
