# Generated by Django 4.2.1 on 2023-05-30 13:52
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_bookpage_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelink',
            name='required_items',
            field=models.ManyToManyField(blank=True, to='book.item'),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='items',
            field=models.ManyToManyField(blank=True, to='book.item'),
        ),
        migrations.AlterField(
            model_name='bookprogress',
            name='items',
            field=models.ManyToManyField(blank=True, to='book.item'),
        ),
    ]
