# Generated by Django 4.2.1 on 2023-05-30 14:03
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_pagelink_required_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagelink',
            name='required_items',
        ),
        migrations.AddField(
            model_name='pagelink',
            name='items',
            field=models.ManyToManyField(blank=True, to='book.item'),
        ),
    ]
