[tool.poetry]
name = "interactivefiction"
version = "0.1.0"
description = ""
authors = ["MATwave <stanislav.matveew@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.2.1"
pre-commit = "^3.3.1"
python-dotenv = "^1.0.0"
mypy = "^1.3.0"
flake8 = "^6.0.0"
isort = "^5.12.0"
pillow = "^9.5.0"
pytest-django = "^4.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
